env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures: { jsx: true }
rules: 
  semi: 2
  no-console: 0 
  import/extensions: 0 
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
