env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures: {
        jsx: true
  }
rules: {
        semi: error,
        no-console: 0,
        import/extensions: 0
}
