name: 'brain-games-action'

on: 
  - push

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            
      - name: npm install
        run: make install
        
      - name: Run liner
        run: make lint
